---
title: "pptmap"
author: "Ryan and Morgan"
date: "9/5/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
#NOT RUN
```{r setup, include=FALSE}
library(raster)
library(dplyr)
library(tidyr)
library(sf)
```


READ in all data
```{r}
ETH0 <- readRDS("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gadm36_ETH_0_sp.rds")
ETH <-   readRDS("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gadm36_ETH_2_sp.rds")
ETH1 <- readRDS("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gadm36_ETH_1_sp.rds")
ETH3 <- readRDS("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gadm36_ETH_3_sp.rds")
DEM <- raster("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gt30e020n40_dem/gt30e020n40.dem")
DEM2 <-raster("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gt30e020s10_dem/gt30e020s10.dem")
ETH_dem <- mask(DEM, ETH0)

```

```{r}
# tif_dem <- raster(x = "/Users/ryankopper/Desktop/R work/PPTmap/map_files/HYP_HR_SR_W/HYP_HR_SR_W.tif")
# ETH_dem2 <- mask(tif_dem, ETH0)
# 
# par(mar = c(0, 0, 1, 0 ))
# plot(ETH_dem2) 

```

```{r}
#Broken into experi + survey based colors
ETH_ex_sites<-subset(ETH3, NAME_3 == "Sibu Sire"| NAME_3 =="Adama" | NAME_3 =="Wondo-Genet" | NAME_3 == "Awasa Zuria"|  NAME_3 == "Awasa") 


ETH_sur_sites<-subset(ETH3, NAME_3 == "Boset"| NAME_3 == "Habro" | NAME_3 == "Tahtay Maychew" | NAME_3 == "Thehulederie") 


ETH_Addis <-subset(ETH, NAME_1 == "Addis Abeba") 




#--------------------------------------------------------------------------
#OLD SITE SELECTIONS

# ETH_ex_sites<-subset(ETH3, NAME_3 == "Sibu Sire"| NAME_3 =="Wondo-Genet" | NAME_3 == "Awasa Zuria"| NAME_3 == "Awasa" ) 
# 
# ETH_sur_sites<-subset(ETH3, NAME_3 == "Boset"| NAME_3 == "Habro" | NAME_3 == "Tahtay Maychew" | NAME_3 == "Thehulederie") 

#ETHIOPIA studies
# ETH_study_sites<-subset(ETH3,NAME_3 =="Adama" | NAME_3 =="Wondo-Genet" | NAME_3 == "Awasa Zuria"| NAME_3 =="Mieso" | NAME_3 == "Boset"| NAME_3 == "Habro" | NAME_3 == "Tahtay Maychew" | NAME_3 == "Thehulederie" | NAME_3 == "Awasa") 
# just_ETH <- st_as_sf(ETH_study_sites) %>% select(NAME_1)
#--------------------------------------------------------------------------
```


```{r}
library(dplyr)
library(sf)
just_ETHex <- st_as_sf(ETH_ex_sites) %>% select(NAME_1)
just_ETHsur <- st_as_sf(ETH_sur_sites) %>% select(NAME_1)

```

Recreate using ggplot2 package
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(sf)
# convert spatial object to a ggplot ready data frame

pts_eth <- st_geometry(st_centroid(just_ETHex))

pt_df <- as.data.frame(pts_eth, region = "id")

pts_eth2 <- st_geometry(st_centroid(just_ETHsur))

pt_df2 <- as.data.frame(pts_eth, region = "id")


#NEED TO FIX THE COODINATES TO X AND Y VALUES
datf <- separate(pt_df, geometry, into = c("lon", "lat"), sep = ",")
datf$lon <- gsub("c\\(", "", datf$lon)
datf$lat <- gsub("\\)", "", datf$lat)

datf2 <- separate(pt_df2, geometry, into = c("lon", "lat"), sep = ",")
datf2$lon <- gsub("c\\(", "", datf2$lon)
datf2$lat <- gsub("\\)", "", datf2$lat)


#plot points
ggplot() +
  geom_point(data = datf, aes(x = lon, y = lat )) + 
  geom_point(data = datf2, aes(x = lon, y = lat )) +
  labs(title = "Plot locations")

#Make DEM
dem.p  <-  rasterToPoints(ETH_dem)
df <-  data.frame(dem.p)
colnames(df) = c("lon", "lat", "alt")

p1 <- ggplot(df, aes(lon,lat)) +
  geom_raster(aes(fill = alt))
  

#Make GADM file for ggplot

outline <- ggplot() + 
  geom_polygon(data=ETH0, aes(long,lat,group=group), fill="gray") +
  geom_path(data=ETH0, aes(long,lat, group=group), color="black",
            size=0.1) 

```


```{r}

#PLOTTING USING RASTER After converting the point files to dots ^
#must run code above under the ggplot process.
png("Eth_ex_sur.png", width = 6, height = 4.5, units = "in", res = 300, pointsize = 12)
par(mar = c(0, 0, 0, 0 ))
plot(ETH0)
plot(ETH_dem, col = socolor, maxpixels = 1e9, add = TRUE, legend = FALSE)
plot(pts_eth, bg = "orangered", pch = 21, add = T)
plot(pts_eth2, bg = "blue3", pch = 21, add = T)
plot(ETH_Addis, col = "dark grey", add = T)
plot(ETH1, add = T)

legend(x = "bottomright", pch = 19, col  = c("orangered", "blue3"),
       legend = c("Experimental studies", "Survey studies"), bty = "n", pt.cex = 2)

dev.off()


```



```{r}
#Using
library(mapview)
 
#URL to find maplayers to be used by mapview
#http://leaflet-extras.github.io/leaflet-providers/preview/

mp <- mapview(pts_eth, col.regions = "red", color = "red", map.types = c("Stamen.TerrainBackground", "Esri.WorldStreetMap"))

#mapshot(mp, file = "map.pdf") #saves to a file but need to figure out extend requirements
mp
```


```{r}
#Create bounding box of the Ethiopia
my_points.df <-
  data.frame(lon = c(32, 47.9, 47.9, 32), 
             lat = c(2.7, 2.7, 15.5, 15.5))
#Using sf package to create a sf spatial object with

library(sf)
my_points.sf <- st_as_sf(my_points.df, coords = c("lon", "lat"), crs = 4326)


my_bbox <- c(xmin = min(my_points.df$lon),
             xmax = max(my_points.df$lon),
             ymin = min(my_points.df$lat),
             ymax = max(my_points.df$lat))

my_bbox.m <- 
  matrix(c(my_bbox['xmin'], my_bbox['xmin'], my_bbox['xmax'], my_bbox['xmax'], my_bbox['xmin'], 
           my_bbox['ymax'], my_bbox['ymin'], my_bbox['ymin'], my_bbox['ymax'], my_bbox['ymax']),
         ncol = 2)
my_bbox.sf <- st_geometry(st_polygon(x = list(my_bbox.m)))
st_crs(my_bbox.sf) <- 4326

my_bbox_buff_2500.sf <- 
  my_bbox.sf %>%
  st_transform(crs = 32632) %>%
  st_buffer(dist = 2500) %>% # 2.5 kilometers
  st_transform(crs = 4326)

my_bbox_buff_5000.sf <- 
  my_bbox.sf %>%
  st_transform(crs = 32632) %>%
  st_buffer(dist = 5000) %>% # 5 kilometers
  st_transform(crs = 4326)

my_bbox_buff_25000.sf <- 
  my_bbox.sf %>%
  st_transform(crs = 32632) %>%
  st_buffer(dist = 25000) %>% # 25 kilometers
  st_transform(crs = 4326)
#This is how my point data look like in its essence.

library(ggplot2)

my_world_map <- map_data('world')
my_world_map <- my_world_map[my_world_map$region %in% ("Ethiopia"),]



gpo <- ggplot() + 
  geom_sf(data = my_points.sf) + 
  geom_sf(data = my_bbox_buff_2500.sf, fill = NA) +
  coord_sf(xlim = c(st_bbox(my_bbox_buff_25000.sf)['xmin'], st_bbox(my_bbox_buff_25000.sf)['xmax']), 
           ylim = c(st_bbox(my_bbox_buff_25000.sf)['ymin'], st_bbox(my_bbox_buff_25000.sf)['ymax'])) +
  geom_polygon(data = my_world_map, 
               aes(x=long, y = lat, group = group,
                   fill = region), colour = 'black', alpha = .4) +
  theme_bw()

gpo
```

```{r}
#NICER DEM WTIHOUT POINTS

#Load DEM and mask to East Africa
library(raster)
DEM <- raster("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gt30e020n40_dem/gt30e020n40.dem")
DEM2 <-raster("/Users/ryankopper/Desktop/R work/PPTmap/map_files/gt30e020s10_dem/gt30e020s10.dem")
ETH_dem <- mask(DEM, ETH0) #clip to Ethiopia

#DEM
dem.raster <- crop(ETH_dem, as(my_bbox_buff_25000.sf, 'Spatial'), snap='out')

dem.m  <-  rasterToPoints(dem.raster)
dem.df <-  data.frame(dem.m)
colnames(dem.df) = c("lon", "lat", "alt")
#Map colors

col <- terrain.colors(10)
socolor <-  rev(col) 

ggplot() +
  geom_raster(data = dem.df, aes(lon, lat, fill = alt), alpha = .99) +
  scale_fill_gradientn(colours = socolor) +
  geom_sf(data = my_bbox_buff_2500.sf, fill = NA) +
  coord_sf(xlim = c(st_bbox(my_bbox_buff_25000.sf)['xmin'], st_bbox(my_bbox_buff_25000.sf)['xmax']), 
           ylim = c(st_bbox(my_bbox_buff_25000.sf)['ymin'], st_bbox(my_bbox_buff_25000.sf)['ymax'])) +
  geom_polygon(data = my_world_map, 
               aes(x=long, y = lat, group = group), fill = NA, colour = 'black') +
  theme_bw() 
 
```


scalebar(data = NULL, location = "bottomright", dist = NULL,
  dist_unit = NULL, transform = NULL, dd2km = NULL, model = NULL,
  height = 0.02, st.dist = 0.02, st.bottom = TRUE, st.size = 5,
  st.color = "black", box.fill = c("black", "white"),
  box.color = "black", border.size = 1, x.min = NULL, x.max = NULL,
  y.min = NULL, y.max = NULL, anchor = NULL, facet.var = NULL,
  facet.lev = NULL, ...)

```{r}
#Hillshading---Works BUT too big of an area 

# slope.raster <- terrain(dem.raster, opt='slope')
# aspect.raster <- terrain(dem.raster, opt='aspect')
# hill.raster <- hillShade(slope.raster, aspect.raster, 40, 270)
# 
# hill.m <- rasterToPoints(hill.raster)
# hill.df <-  data.frame(hill.m)
# colnames(hill.df) <- c("lon", "lat", "hill")
# #
# #
# ggplot() +
#   geom_raster(data = hill.df, aes(lon, lat, fill = hill), alpha = .95) +
#   scale_fill_gradientn(colours = socolor) +
#   geom_sf(data = my_bbox_buff_2500.sf, fill = NA) +
#   coord_sf(xlim = c(st_bbox(my_bbox_buff_25000.sf)['xmin'], st_bbox(my_bbox_buff_25000.sf)['xmax']),
#            ylim = c(st_bbox(my_bbox_buff_25000.sf)['ymin'], st_bbox(my_bbox_buff_25000.sf)['ymax'])) +
#   geom_polygon(data = my_world_map,
#                aes(x=long, y = lat, group = group), fill = NA, colour = 'black') +
#   theme_bw()


```

```{r}
library(dismo)
library(ggmap)
#{https://developers.google.com/maps/documentation/maps-static/get-api-key}
register_google(key = "") #need to create an API from ggogle cloud eacht time

Just_Ethiopia
ggmap(get_map(location=c(40.50, 9.0 ), zoom=6, scale=2), type = "terrain")




East_Africa <-
ggmap(get_map(location=c(38.50, 2.0 ), zoom=5, scale=2), type = "terrain")



```
