---
title: "Index Website for PPT Figures"
authors: "Ryan Kopper & Morgan Ruelle"
output:
  html_document:
    theme: spacelab
    toc: true
    toc_depth: 3
    toc_float: true
---



```{r, include=FALSE}
library(networkD3)
library(tidyverse)
library(readxl)
library(readr)
#4 plot
library(scales)
library(RColorBrewer)
library(paletteer)

```

```{r, include=FALSE}


df <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Table of journals included.xlsx", sheet = "included")

#df <- read_excel("C:/Users/Morgan/OneDrive - Clark University/Ryan Kopper Research/Push Pull Systematic Review/Table of journals included.xlsx", sheet = "included")

```

```{r, include=FALSE}

df <- df %>% 
    mutate(Location = strsplit(Location, ",")) %>% 
    unnest(Location) %>% mutate(Type_research = strsplit(Type_research, ",")) %>% unnest(Type_research) %>% mutate(date_cat=cut(Date, breaks = c(-Inf, 2004, 2009, 2014, Inf), labels = c("2000 to 2004","2005 to 2009","2010 to 2014","2015 to 2019"))) %>% group_by(date_cat, `Type_research`, Location) %>% summarise(count = n())

```


```{r, include=FALSE}
#Stack by experiment and survey. use Facet grid or dodge (countries)

figure1 = ggplot(df, aes(x = Location, y = count, fill = Type_research))+
  geom_bar(stat = "identity")+
  theme_bw()+
  facet_grid(cols=vars(date_cat),labeller = label_wrap_gen(width = 10,
                                                  multi_line = TRUE),
             space = "free_x", scales = "free_x")+
  theme(axis.text.x = element_text(size = 10,angle=90,vjust=0.5,hjust=1),
        legend.position = "bottom")+
  ylab("Number of studies")+
  scale_fill_manual(name = "Type of study",
                    labels = c("field experiment", "farmer survey"),
                    values = c("#0072B2", "#D55E00"))
```

```{r, dpi= 300, fig.width = 6, echo=FALSE, include=FALSE}
## Country charts

figure1
```


```{r, include=FALSE}
## load libraries
library(dplyr)
#info sheet https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf

library(networkD3)
library(tidyverse)
library(readxl)
library(readr)
#4 plot
library(scales)
library(RColorBrewer)
library(paletteer)
#Package 'ggthemes' needed. Please install it by running `install.packages('ggthemes')

#4Sankey
library(sankeyD3)
# Installation
#install.packages('devtools')
#devtools::install_github("fbreitwieser/sankeyD3")


```



```{r, include=FALSE}

##### Choose Data
# 
# Choose between the next 2 chunks Experiment or Survey data sets 
# comment out the one not using...

#### EXPERIMENT

# Set working directory for Ryan
#setwd("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/")

# Set working directory for Morgan
#setwd("C:/Users/Morgan/OneDrive - Clark University/Ryan Kopper Research/Push Pull Systematic Review/")
#*The setting of the WD above did not work with the Knit*
```


```{r, include=FALSE}

#Experiment paths

Relationships <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Field Experiment Data for Analysis 2020_07_20.xlsx", sheet = "Relationships")


Independent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Field Experiment Data for Analysis 2020_07_20.xlsx", sheet = "Independent recode")


Dependent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Field Experiment Data for Analysis 2020_07_20.xlsx", sheet = "Dependent recode")

```

```{r, include=FALSE}
## Format Data

joined_long <- left_join( Relationships, Independent_recode, by = "Independent_variable") %>% left_join(Dependent_recode, by = "Dependent_variable") %>%  select(Title, Independent_variable_recode, Dependent_variable_recode) %>% distinct() %>% group_by(Independent_variable_recode, Dependent_variable_recode) %>% summarise(count = n()) 


#ordering independent and dependent variables

indi_order <- group_by(joined_long, Independent_variable_recode) %>%  summarise(total = sum(count)) %>% arrange(total, by_group = TRUE) %>% pull(Independent_variable_recode)

dep_order <- group_by(joined_long, Dependent_variable_recode) %>%
summarise(total = sum(count)) %>% arrange(total, by_group = TRUE) %>% pull(Dependent_variable_recode)


```


```{r, include=FALSE}


figure2 <- joined_long %>% mutate(Independent_variable_recode = factor(Independent_variable_recode,levels = rev(indi_order)), Dependent_variable_recode = factor(Dependent_variable_recode,levels = dep_order)) %>% ggplot(aes(x = Independent_variable_recode, y = Dependent_variable_recode, color = count)) + geom_point(aes(size = count)) + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 90, vjust = .5 ,  hjust = 1), axis.text.y = element_text(size = 10), legend.position = "bottom") +  guides(size = FALSE) + ylab("Dependent variable") + xlab("Independent variable")  +
scale_colour_paletteer_c("ggthemes::Classic Area Red-Green", breaks = c(9, 5, 3, 2, 1)) + scale_size_continuous(breaks = c(9, 5, 3, 2, 1)) + guides(color = guide_legend(title = "Number of\nstudies"), size = guide_legend(title = "Number of\nstudies")) 


```



```{r , fig.height= 7, fig.width= 10, dpi= 300, echo=FALSE,include=FALSE}

## Experiment variable matrix

figure2

```


## Experiment Sankey diagram
```{r, include=FALSE}
# create nodes dataframe

distinct_rel <- left_join( Relationships, Independent_recode,
                           by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
  distinct(Title, Independent_variable_recode,
           Dependent_variable_recode, Independent_broad_category,
           Dependent_broad_category)

# Adding significance the distinct relations
distinct_rel_sig <- Relationships %>% 
  left_join(Independent_recode, by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
  select(Independent_variable_recode, Dependent_variable_recode, Relationship) %>% 
  group_by(Independent_variable_recode, Dependent_variable_recode) %>%
  summarise(sig = sum(Relationship=="significant"),
            not_sig = sum(Relationship=="not significant"),
            mixed = sum(Relationship=="mixed"),
            total = n()) %>%  
  mutate(significance = if_else(sig==total,"sig",
                                if_else(not_sig==total,"not_sig","mixed"))) %>%
  full_join(distinct_rel) %>% 
  select(Title,Independent_variable_recode,Independent_broad_category,
         Dependent_variable_recode,Dependent_broad_category,significance)
```

```{r, include=FALSE}
BIV_2_BDV <- distinct_rel_sig %>%
  select(Title, Independent_broad_category, Dependent_broad_category,significance) %>%
  group_by(Independent_broad_category, Dependent_broad_category,significance) %>%
  summarise(count = n()) %>% rename(target = Dependent_broad_category,
                                    source = Independent_broad_category,
                                    link_group = significance)

IV_2_BIV <- distinct_rel %>%
  group_by(Independent_variable_recode, Independent_broad_category) %>%
  summarise(count = n()) %>%
  rename(source = Independent_variable_recode, target = Independent_broad_category) %>% 
  mutate(link_group="subset")


DV_2_BDV <- distinct_rel %>%
  group_by(Dependent_variable_recode, Dependent_broad_category) %>%
  summarise(count = n()) %>%
  rename(target = Dependent_variable_recode, source = Dependent_broad_category) %>% 
  mutate(link_group="subset")

joined_long <- bind_rows(IV_2_BIV , DV_2_BDV, BIV_2_BDV)

```


```{r, include=FALSE}
#### Create Nodes
# create nodes dataframe

IV <- unique(Independent_recode$Independent_variable_recode)
DV <- unique(Dependent_recode$Dependent_variable_recode)
BIV <- unique(Independent_recode$Independent_broad_category)
BDV <- unique(Dependent_recode$Dependent_broad_category)
total_var <- length(IV) + length(DV) + length(BIV) + length(BDV) - 1

nodes <- data.frame(key = 0:total_var,
                   variable = as.factor(c(as.character(IV),as.character(DV),
                                          as.character(BIV), as.character(BDV)))) %>% 
  mutate(node_group="all")


```


```{r, include=FALSE}
#### Create links dataframe and rename 

links <- joined_long %>%
  inner_join(nodes,  by = c("source" = "variable"))%>%
  rename(source_key = key) %>% 
  inner_join(nodes,  by = c("target" = "variable")) %>%
  rename(target_key = key) %>% 
  select(source,target,source_key,target_key,count,link_group)

```


```{r, include=FALSE}
my_color <- 'd3.scaleOrdinal() .domain(["all","mixed","not_sig","sig","subset"]) .range(["tan", "orange" , "yellow", "red","lightgrey"])'

figure3 <- sankeyD3::sankeyNetwork(Links = links,
                        Nodes = nodes,
                        Source = 'source_key', 
                        Target = 'target_key',
                        Value = 'count',
                        NodeID = "variable",
                        LinkGroup = "link_group",
                        NodeGroup = "node_group",
                        colourScale = my_color,
                        fontSize = 12,
                        fontFamily = "sans-serif",
                        orderByPath = F,
                        showNodeValues = FALSE,
                        nodePadding = 10,
                        nodeWidth = 30,
                        align="center",
                        linkOpacity = 0.4,
                        curvature = 0.4,
                        dragY = TRUE,
                        title = NULL,
                        iterations = 0)


```


```{r, fig.height= 6, fig.width= 8, dpi= 100, echo=FALSE}
figure3
```




```{r, include=FALSE}
## Survey variable matrix

#Survey paths
Relationships <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Relationships")

Independent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Independent recode")

Dependent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Dependent recode")
```

```{r, include=FALSE}

df <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Table of journals included.xlsx", sheet = "included")

#df <- read_excel("C:/Users/Morgan/OneDrive - Clark University/Ryan Kopper Research/Push Pull Systematic Review/Table of journals included.xlsx", sheet = "included")

```

```{r, include=FALSE}

#Survey paths
Relationships <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Relationships")

Independent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Independent recode")

Dependent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Dependent recode")

```


```{r, include=FALSE}
## Format Data

joined_long <- left_join( Relationships, Independent_recode, by = "Independent_variable") %>% left_join(Dependent_recode, by = "Dependent_variable") %>%  select(Title, Independent_variable_recode, Dependent_variable_recode) %>% distinct() %>% group_by(Independent_variable_recode, Dependent_variable_recode) %>% summarise(count = n()) 


#ordering independent and dependent variables

indi_order <- group_by(joined_long, Independent_variable_recode) %>%  summarise(total = sum(count)) %>% arrange(total, by_group = TRUE) %>% pull(Independent_variable_recode)

dep_order <- group_by(joined_long, Dependent_variable_recode) %>%
summarise(total = sum(count)) %>% arrange(total, by_group = TRUE) %>% pull(Dependent_variable_recode)


```


```{r, include=FALSE}


figure4 <- joined_long %>% mutate(Independent_variable_recode = factor(Independent_variable_recode,levels = rev(indi_order)), Dependent_variable_recode = factor(Dependent_variable_recode,levels = dep_order)) %>% ggplot(aes(x = Independent_variable_recode, y = Dependent_variable_recode, color = count)) + geom_point(aes(size = count)) + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 90, vjust = .5 ,  hjust = 1), axis.text.y = element_text(size = 10), legend.position = "bottom") +  guides(size = FALSE) + ylab("Dependent variable") + xlab("Independent variable")  +
scale_colour_paletteer_c("ggthemes::Classic Area Red-Green", breaks = c(9, 5, 3, 2, 1)) + scale_size_continuous(breaks = c(9, 5, 3, 2, 1)) + guides(color = guide_legend(title = "Number of\nstudies"), size = guide_legend(title = "Number of\nstudies")) 


```


```{r , fig.height= 7, fig.width= 10, dpi= 300, echo=FALSE,include=FALSE}
figure4

```




## Survey Sankey diagram

```{r, include=FALSE}
# create nodes dataframe

distinct_rel <- left_join( Relationships, Independent_recode,
                           by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
  distinct(Title, Independent_variable_recode,
           Dependent_variable_recode, Independent_broad_category,
           Dependent_broad_category)

# Adding significance the distinct relations
distinct_rel_sig <- Relationships %>% 
  left_join(Independent_recode, by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
  select(Independent_variable_recode, Dependent_variable_recode, Relationship) %>% 
  group_by(Independent_variable_recode, Dependent_variable_recode) %>%
  summarise(sig = sum(Relationship=="significant"),
            not_sig = sum(Relationship=="not significant"),
            mixed = sum(Relationship=="mixed"),
            total = n()) %>%  
  mutate(significance = if_else(sig==total,"sig",
                                if_else(not_sig==total,"not_sig","mixed"))) %>%
  full_join(distinct_rel) %>% 
  select(Title,Independent_variable_recode,Independent_broad_category,
         Dependent_variable_recode,Dependent_broad_category,significance)
```

```{r, include=FALSE}
BIV_2_BDV <- distinct_rel_sig %>%
  select(Title, Independent_broad_category, Dependent_broad_category,significance) %>%
  group_by(Independent_broad_category, Dependent_broad_category,significance) %>%
  summarise(count = n()) %>% rename(target = Dependent_broad_category,
                                    source = Independent_broad_category,
                                    link_group = significance)

IV_2_BIV <- distinct_rel %>%
  group_by(Independent_variable_recode, Independent_broad_category) %>%
  summarise(count = n()) %>%
  rename(source = Independent_variable_recode, target = Independent_broad_category) %>% 
  mutate(link_group="subset")


DV_2_BDV <- distinct_rel %>%
  group_by(Dependent_variable_recode, Dependent_broad_category) %>%
  summarise(count = n()) %>%
  rename(target = Dependent_variable_recode, source = Dependent_broad_category) %>% 
  mutate(link_group="subset")

joined_long <- bind_rows(IV_2_BIV , DV_2_BDV, BIV_2_BDV)

```


```{r, include=FALSE}
#### Create Nodes
# create nodes dataframe

IV <- unique(Independent_recode$Independent_variable_recode)
DV <- unique(Dependent_recode$Dependent_variable_recode)
BIV <- unique(Independent_recode$Independent_broad_category)
BDV <- unique(Dependent_recode$Dependent_broad_category)
total_var <- length(IV) + length(DV) + length(BIV) + length(BDV) - 1

nodes <- data.frame(key = 0:total_var,
                   variable = as.factor(c(as.character(IV),as.character(DV),
                                          as.character(BIV), as.character(BDV)))) %>% 
  mutate(node_group="all")


```


```{r, include=FALSE}
#### Create links dataframe and rename 

links <- joined_long %>%
  inner_join(nodes,  by = c("source" = "variable"))%>%
  rename(source_key = key) %>% 
  inner_join(nodes,  by = c("target" = "variable")) %>%
  rename(target_key = key) %>% 
  select(source,target,source_key,target_key,count,link_group)

```


```{r, include=FALSE}
my_color <- 'd3.scaleOrdinal() .domain(["all","mixed","not_sig","sig","subset"]) .range(["tan", "orange" , "yellow", "red","lightgrey"])'

figure5 <- sankeyD3::sankeyNetwork(Links = links,
                        Nodes = nodes,
                        Source = 'source_key', 
                        Target = 'target_key',
                        Value = 'count',
                        NodeID = "variable",
                        LinkGroup = "link_group",
                        NodeGroup = "node_group",
                        colourScale = my_color,
                        fontSize = 12,
                        fontFamily = "sans-serif",
                        orderByPath = F,
                        showNodeValues = FALSE,
                        nodePadding = 10,
                        nodeWidth = 30,
                        align="center",
                        linkOpacity = 0.4,
                        curvature = 0.4,
                        dragY = TRUE,
                        title = NULL,
                        iterations = 0)


```

```{r, fig.height= 6, fig.width= 8, dpi= 100, echo=FALSE}
figure5
```

