---
title: "Survey variables analysis to produce Sanky Diagram"
author: "Ryan Kopper"
date: "5/22/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
## load libraries
library(dplyr)
#info sheet https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf

library(networkD3)
library(tidyverse)
library(readxl)
library(readr)
#library(xlsx)
```

Choose between the next 2 chunks Experiment or Survey data sets 
comment out the one not using...

```{r}
#EXPERIMENT

#Read in each sheet individually which creates a Tibble for each.

Relationships <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Experiment relationships 2020_06_11.xlsx", sheet = "Relationships")
#Relationships <- data.frame(lapply(Relationships, as.factor))


Independent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Experiment relationships 2020_06_11.xlsx", sheet = "Independent recode")
#Independent_recode <- data.frame(lapply(Independent_recode, as.factor))

Dependent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Experiment relationships 2020_06_11.xlsx", sheet = "Dependent recode")
#Dependent_recode <- data.frame(lapply(Dependent_recode, as.factor))

```


```{r}
#SURVEY

# Relationships <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey relationships 2020_05_19.xlsx", sheet = "Relationships")
# #Relationships <- data.frame(lapply(Relationships, as.factor))
# 
# 
# Independent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey relationships 2020_05_19.xlsx", sheet = "Independent recode")
# #Independent_recode <- data.frame(lapply(Independent_recode, as.factor))
# 
# Dependent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey relationships 2020_05_19.xlsx", sheet = "Dependent recode")
# #Dependent_recode <- data.frame(lapply(Dependent_recode, as.factor))
```


```{r}

joined_long <- left_join( Relationships, Independent_recode, by = "Independent_variable") %>% left_join(Dependent_recode, by = "Dependent_variable") %>%  select(Independent_variable_recode, Dependent_variable_recode) %>% group_by(Independent_variable_recode, Dependent_variable_recode) %>% summarise(count = n()) 

joined_matrix <- left_join( Relationships, Independent_recode, by = "Independent_variable") %>% left_join(Dependent_recode, by = "Dependent_variable") %>%  select(Independent_variable_recode, Dependent_variable_recode) %>% group_by(Independent_variable_recode, Dependent_variable_recode) %>% summarise(count = n()) %>% spread(key = Dependent_variable_recode, value = count) %>% replace(is.na(.), 0 ) 

# glimpse(joined_tibble)
# str(joined_tibble)

```


```{r}
#Bubble plot

library(scales)
library(RColorBrewer)
library(paletteer)
#Package 'ggthemes' needed. Please install it by running `install.packages('ggthemes')


ggplot(joined_long, aes(x = Dependent_variable_recode, y = Independent_variable_recode, color = count )) + geom_point(aes(size = count)) + theme(axis.text.x = element_text(angle = 90, vjust = .5 ,  hjust = 1)) + scale_x_discrete(labels = label_wrap(20)) + scale_y_discrete(labels = label_wrap(30)) 


#show this one-has green as highest number
ggplot(joined_long, aes(x = Dependent_variable_recode, y = Independent_variable_recode, color = count)) + geom_point(aes(size = count)) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = .5 ,  hjust = 1)) + scale_x_discrete(labels = label_wrap(20)) + scale_y_discrete(labels = label_wrap(30)) + guides(size = FALSE) + xlab("Dependent variable") + ylab("Independent variable")  +
scale_colour_paletteer_c("ggthemes::Classic Area Red-Green") + guides(color = guide_legend(title = "Number of\nstudies"), size = guide_legend(title = "Number of\nstudies")) 


```

#-------------------------------------------------------------------------------
#using paletteer package

```{r}
#show this one--has blue as highest number

g1 <- ggplot(joined_long, aes(x = Dependent_variable_recode, y = Independent_variable_recode, color = count)) + geom_point(aes(size = count)) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = .5 ,  hjust = 1)) + scale_x_discrete(labels = label_wrap(20)) + scale_y_discrete(labels = label_wrap(30)) + guides(size = FALSE) + xlab("Dependent variable") + ylab("Independent variable")

x <- paletteer_c("ggthemes::Classic Area Red-Green", 10)

g1 + scale_color_gradient(low = x) + guides(color = guide_legend(title = "Number of\nstudies"), size = guide_legend(title = "Number of\nstudies")) 

```

SANKEY DIAGRAMS

CREATING IT IN R
```{r}
# create nodes dataframe

IV <- unique(joined_long$Independent_variable_recode)
DV <- unique(joined_long$Dependent_variable_recode)
node <- data.frame(key = 0:30, variable = as.factor(c(as.character(IV), as.character(DV))))


#create links dataframe and rename 
links <- joined_long %>% inner_join(node,  by = c("Independent_variable_recode" = "variable")) %>% rename(IV_key = key) %>% 
  inner_join(node,  by = c("Dependent_variable_recode" = "variable")) %>% rename(DV_key = key)


# sankeyNetwork(Links = links, Nodes = node, Source = 'IV_key', 
#               Target = 'DV_key', Value = 'count', NodeID = "variable", 
#               fontSize = 12, nodeWidth = 20, 
#               fontFamily = "sans serif", iterations = 0)


```

```{r}
#LinkGroup
#when we bring in significant and non
#https://www.r-graph-gallery.com/322-custom-colours-in-sankey-diagram.html    

#rating significance

joined_long_sig <- Relationships %>% filter(Relationship == "significant") %>%
  left_join(Independent_recode, by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
  select(Independent_variable_recode, Dependent_variable_recode) %>%
  group_by(Independent_variable_recode, Dependent_variable_recode) %>%
  summarise(significant = n()) %>%
  full_join(joined_long) %>% 
  replace(is.na(.), 0 ) %>%
  mutate(significance = if_else(significant == 0, "not_sig", if_else(significant == count, "sig", "mixed")))

# create nodes dataframe

IVsig <- unique(joined_long_sig$Independent_variable_recode)
DVsig <- unique(joined_long_sig$Dependent_variable_recode)

nodesig <- data.frame(key = 0:30, variable = as.factor(c(as.character(IVsig), as.character(DVsig))))

linkssig <- joined_long_sig %>% inner_join(nodesig,  by = c("Independent_variable_recode" = "variable")) %>% rename(IV_key = key) %>% 
  inner_join(nodesig,  by = c("Dependent_variable_recode" = "variable")) %>% rename(DV_key = key)

linkssig <- data.frame(linkssig)
```


```{r}
#create links dataframe and rename 

# Add a 'group' column to each node. Here I decide to put all of them in the same group to make them grey

#node$group <- as.factor(c("group"))
 
# Give a color for each group:
# sig = green
# mixed yellow
# not sig = grey


# Put all notes in one group for now
nodesig$group <- as.factor(c("node_group"))

# Set up colors for groups
my_color <- 'd3.scaleOrdinal() .domain(["node_group","mixed","not_sig", "sig"]) .range(["tan", "lightgreen" , "lightgrey", "darkgreen"])'


# sankeyNetwork(Links = linkssig,
#               Nodes = nodesig,
#               Source = 'IV_key', 
#               Target = 'DV_key',
#               Value = 'count',
#               NodeID = "variable", 
#               LinkGroup = "significance",
#               NodeGroup = "group",
#               colourScale = my_color,
#               fontSize = 16)




# nb.cols <- 34
# my_color <- colorRampPalette(brewer.pal(8, "Set2"))(nb.cols)
# 
# node_names <- as.character(unique(nodesig$variable))
# link_names <- as.character(unique(linkssig$significance))
# all_names <- c(node_names, link_names)
# 
# new_color <- JS('d3.scaleOrdinal() .domain([all_names]) .range([my_color])')

# Make the Network

#

# sankeyNetwork(Links = linkssig,
#               Nodes = nodesig,
#               Source = 'IV_key', 
#               Target = 'DV_key',
#               Value = 'count',
#               NodeID = "variable", 
#               colourScale = my_color,
#               LinkGroup = "significance",
#               NodeGroup = "variable",
#               fontSize = 14,
#               fontFamily = "sans serif", iterations = 0)

```

The following Sankey is the one to use---features red, grey and green to dipict significance
```{r}


# Try some new options in the developer version
# https://rdrr.io/github/fbreitwieser/sankeyD3/man/sankeyNetwork.html
# I added some of these but there are a lot more to play with

# Installation
#install.packages('devtools')
#devtools::install_github("fbreitwieser/sankeyD3")

#https://github.com/fbreitwieser/sankeyD3
library(sankeyD3)

my_color <- 'd3.scaleOrdinal() .domain(["node_group","not_sig","mixed","sig"]) .range(["tan","red","dimgrey", "green"])'

sankeyD3::sankeyNetwork(Links = linkssig,
              Nodes = nodesig,
              Source = 'IV_key', 
              Target = 'DV_key',
              Value = 'count',
              NodeID = "variable", 
              LinkGroup = "significance",
              NodeGroup = "group",
              colourScale = my_color,
              fontSize = 12,
              fontFamily = "sans-serif",
              orderByPath = TRUE,
              showNodeValues = FALSE,
              nodePadding = 10,
              nodeWidth = 30,
              align="center",
              linkOpacity = 0.4,
              curvature = 0.4,
              dragY = TRUE,
              title = NULL,
              iterations = 0)




```


