---
title: Experiment & survey studies variable analysis to produce visuals (Matrix and
  Sankey)
author: "Ryan Kopper and Morgan Ruelle"
date: "6/26/2020"
output:
  html_document: default
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
## load libraries
library(dplyr)
#info sheet https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf

library(networkD3)
library(tidyverse)
library(readxl)
library(readr)
#4 plot
library(scales)
library(RColorBrewer)
library(paletteer)
#Package 'ggthemes' needed. Please install it by running `install.packages('ggthemes')

#4Sankey
library(sankeyD3)
# Installation
#install.packages('devtools')
#devtools::install_github("fbreitwieser/sankeyD3")


```

##### Choose Data

Choose between the next 2 chunks Experiment or Survey data sets 
comment out the one not using...

#### EXPERIMENT

```{r, inciude=FALSE}
# Set working directory for Ryan
#setwd("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/")

# Set working directory for Morgan
#setwd("C:/Users/Morgan/OneDrive - Clark University/Ryan Kopper Research/Push Pull Systematic Review/")
```
*The setting of the WD above did not work with the Knit*

```{r, inciude=FALSE}

#Experiment paths
# 
# Relationships <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Field Experiment Data for Analysis 2020_07_20.xlsx", sheet = "Relationships")
# 
# 
# Independent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Field Experiment Data for Analysis 2020_07_20.xlsx", sheet = "Independent recode")
# 
# 
# Dependent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Field Experiment Data for Analysis 2020_07_20.xlsx", sheet = "Dependent recode")

```

```{r, inciude=FALSE}
#Survey paths

Relationships <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Relationships")

Independent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Independent recode")

Dependent_recode <- read_excel("/Users/ryankopper/Clark University/Morgan Ruelle - Ryan Kopper Research/Push Pull Systematic Review/Survey Data for Analysis 2020_07_20.xlsx", sheet = "Dependent recode")


```

##### Format Data
```{r, inciude=FALSE}

joined_long <- left_join( Relationships, Independent_recode, by = "Independent_variable") %>% left_join(Dependent_recode, by = "Dependent_variable") %>%  select(Title, Independent_variable_recode, Dependent_variable_recode) %>% distinct() %>% group_by(Independent_variable_recode, Dependent_variable_recode) %>% summarise(count = n()) 


#ordering independent and dependent variables

indi_order <- group_by(joined_long, Independent_variable_recode) %>%  summarise(total = sum(count)) %>% arrange(total, by_group = TRUE) %>% pull(Independent_variable_recode)

dep_order <- group_by(joined_long, Dependent_variable_recode) %>%
summarise(total = sum(count)) %>% arrange(total, by_group = TRUE) %>% pull(Dependent_variable_recode)


```

#### Bubble plot

```{r , fig.height= 7, fig.width= 10, dpi= 300, inciude=FALSE}


figure2 <- joined_long %>% mutate(Independent_variable_recode = factor(Independent_variable_recode,levels = rev(indi_order)), Dependent_variable_recode = factor(Dependent_variable_recode,levels = dep_order)) %>% ggplot(aes(x = Independent_variable_recode, y = Dependent_variable_recode)) + geom_point(aes(size = count, fill = count), pch = 21) + theme_bw() + theme(axis.text.x = element_text(size = 10, angle = 90, vjust = .5 ,  hjust = 1), axis.text.y = element_text(size = 10), legend.position = "bottom") +  guides(size = FALSE) + ylab("Dependent variable") + xlab("Independent variable")  +
scale_fill_distiller(type = "seq", palette = "Greens", direction = 1, breaks = c(9, 5, 3, 2, 1)) + scale_size_continuous(breaks = c(9, 5, 3, 2, 1)) + guides(fill = guide_legend(title = "Number of\nstudies"), size = guide_legend(title = "Number of\nstudies")) 

```


```{r, inciude=FALSE}
tab <- joined_long %>% mutate(Independent_variable_recode = factor(Independent_variable_recode,levels = rev(indi_order)), Dependent_variable_recode = factor(Dependent_variable_recode,levels = dep_order)) 
```



```{r , fig.height= 7, fig.width= 10, dpi= 300}

#png("Matrix_experi.png", width = 6.5, height = 7, units = "in", res = 300, pointsize = 7)

figure2

#dev.off()
```


#### SANKEY DIAGRAMS


```{r, inciude=FALSE}
# create nodes dataframe

distinct_rel <- left_join( Relationships, Independent_recode,
                           by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
  distinct(Title, Independent_variable_recode,
           Dependent_variable_recode, Independent_broad_category,
           Dependent_broad_category)

# Adding significance the distinct relations
distinct_rel_sig <- Relationships %>% 
  left_join(Independent_recode, by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
  select(Title,Independent_variable_recode, Dependent_variable_recode, Relationship) %>% 
  group_by(Title,Independent_variable_recode, Dependent_variable_recode) %>%
  summarise(sig = sum(Relationship=="significant"),
            not_sig = sum(Relationship=="not significant"),
            mixed = sum(Relationship=="mixed"),
            total = n()) %>%  
  mutate(significance = if_else(sig==total,"sig",
                                if_else(not_sig==total,"not_sig","mixed"))) %>%
  full_join(distinct_rel) %>% 
  select(Title,Independent_variable_recode,Independent_broad_category,
         Dependent_variable_recode,Dependent_broad_category,significance)
```

```{r, inciude=FALSE}
BIV_2_BDV <- distinct_rel_sig %>%
  select(Title, Independent_broad_category, Dependent_broad_category,significance) %>%
  group_by(Independent_broad_category, Dependent_broad_category,significance) %>%
  summarise(count = n()) %>% rename(target = Dependent_broad_category,
                                    source = Independent_broad_category,
                                    link_group = significance)

IV_2_BIV <- distinct_rel %>%
  group_by(Independent_variable_recode, Independent_broad_category) %>%
  summarise(count = n()) %>%
  rename(source = Independent_variable_recode, target = Independent_broad_category) %>% 
  mutate(link_group="subset")


DV_2_BDV <- distinct_rel %>%
  group_by(Dependent_variable_recode, Dependent_broad_category) %>%
  summarise(count = n()) %>%
  rename(target = Dependent_variable_recode, source = Dependent_broad_category) %>% 
  mutate(link_group="subset")

joined_long <- bind_rows(IV_2_BIV , DV_2_BDV, BIV_2_BDV)

```

#### Create Nodes
```{r, inciude=FALSE}
# create nodes dataframe

IV <- unique(Independent_recode$Independent_variable_recode)
DV <- unique(Dependent_recode$Dependent_variable_recode)
BIV <- unique(Independent_recode$Independent_broad_category)
BDV <- unique(Dependent_recode$Dependent_broad_category)
total_var <- length(IV) + length(DV) + length(BIV) + length(BDV) - 1

nodes <- data.frame(key = 0:total_var,
                   variable = as.factor(c(as.character(IV),as.character(DV),
                                          as.character(BIV), as.character(BDV)))) %>% 
  mutate(node_group="all")


```

#### Create links dataframe and rename 
```{r, inciude=FALSE}

links <- joined_long %>%
  inner_join(nodes,  by = c("source" = "variable"))%>%
  rename(source_key = key) %>% 
  inner_join(nodes,  by = c("target" = "variable")) %>%
  rename(target_key = key) %>% 
  select(source,target,source_key,target_key,count,link_group)

```


```{r, inciude=FALSE}
my_color <- 'd3.scaleOrdinal() .domain(["all","mixed","not_sig","sig","subset"]) .range(["tan", "#4682b4" , "#8b8682", "#551a8b","tan"])'

figure4 <- sankeyD3::sankeyNetwork(Links = links,
                        Nodes = nodes,
                        Source = 'source_key', 
                        Target = 'target_key',
                        Value = 'count',
                        NodeID = "variable",
                        LinkGroup = "link_group",
                        NodeGroup = "node_group",
                        colourScale = my_color,
                        fontSize = 12,
                        fontFamily = "sans-serif",
                        orderByPath = F,
                        showNodeValues = FALSE,
                        nodePadding = 10,
                        nodeWidth = 15,
                        align="center",
                        linkOpacity = 0.5,
                        curvature = 0.4,
                        dragY = TRUE,
                        title = NULL,
                        iterations = 0)


```

```{r, fig.height= 6, fig.width= 8, dpi= 100}
tiff(filename = "/Users/ryankopper/Desktop/R work/pptmap.github.com/PPT_matrix_sankey.tiff",
     width = 3, height = 4, res = 300, pointsize = 7,
     bg = "white")


figure4

dev.off()

```


# saving a sankey as a png?
# https://hafen.github.io/rbokeh/articles/rbokeh.html

```{r}
# library(rbokeh)
# sn <- sankeyNetwork(Links = Energy$links, Nodes = Energy$nodes, Source = "source",
#           Target = "target", Value = "value", NodeID = "name",
#           units = "TWh", fontSize = 12, nodeWidth = 30)
# widget2png(sn, "sankey.png")


#  OR capture webshot

#webshot::webshot("file.html")

#https://stackoverflow.com/questions/35056733/how-to-capture-html-output-as-png-in-r
```


#---------------------------------------------

Number of significant results for text

```{r, include=FALSE}

sig_results <-left_join( Relationships, Independent_recode,
                           by = "Independent_variable") %>%
  left_join(Dependent_recode, by = "Dependent_variable") %>%
   select(Title, Independent_variable_recode, Dependent_variable_recode,
          Relationship, Direction) %>% group_by(Title,Independent_variable_recode, Dependent_variable_recode) %>%
  summarise(pos = sum(Direction == "positive"),
            neg = sum(Direction == "negative"),
            not_app = sum(Direction=="NA"),
            total = n()) %>%  
  mutate(Direction = if_else(pos == total,"pos",
                                if_else(neg == total,"neg",
                                        if_else(not_app == total, "NA", "mixed")))) %>%
  select(Title, Independent_variable_recode,
           Dependent_variable_recode, Direction) %>% left_join(distinct_rel_sig) %>% 
  group_by(Independent_variable_recode,
           Dependent_variable_recode, significance, Direction) %>% summarise(count = n())

```
